name: Universal Build (Android, Windows, Mac)

on:
  push:
    branches:
      - main
      - master

jobs:
  build_android:
    name: Android Build 🤖
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tasbih_F_Android
          path: build/app/outputs/flutter-apk/app-release.apk

  build_macos:
    name: MacOS Build 🍏
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --release
      - name: Upload Mac App
        uses: actions/upload-artifact@v4
        with:
          name: Tasbih_F_MacOS
          path: build/macos/Build/Products/Release/*.app

  build_windows:
    name: Windows Build 🪟
    runs-on: windows-latest
    # Added permissions to help with runner access
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: Tasbih_F_Windows
          # Search everywhere in build/windows to find the exe regardless of folder structure
          path: build/windows/**/*.exe
